# Generated by Django 4.2.6 on 2023-10-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=60)),
                ('numpags', models.SmallIntegerField()),
                ('autor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NumUsuario', models.IntegerField()),
                ('nif', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FecPrestamo', models.DateField(verbose_name='Inicio')),
                ('FecDevolucion', models.DateField(auto_now=True, verbose_name='Fin')),
                ('libro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.libro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
