# Generated by Django 4.2.6 on 2023-10-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_autor_id_alter_libro_id_alter_prestamos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='FecDevolucion',
            field=models.DateField(verbose_name='Fin'),
        ),
    ]
